title: Maaruf Vazifdar
logo: /assets/img/maaruf.jpeg
email: 
description: Master of Engineering - Robotics at University of Maryland, College Park
show_downloads: false
google_analytics:
theme: jekyll-theme-minimalist
color-scheme: dark
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
